services:
  - type: web
    name: pulse-ai-frontend
    env: node
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health